FROM ubuntu:18.04
MAINTAINER Docker xiyangxixian <2554758802@qq.com>
RUN apt-get update
RUN apt-get install -y python3 python3-pip vim git
RUN ["pip3", "install", "Flask", "pymysql"]
RUN mkdir /soarweb
RUN ["git", "clone", "https://github.com/xiyangxixian/soar-web.git", "/soarweb/app"]
RUN chmod a+x /soarweb/app/soar
RUN chmod a+w /soarweb/app/tmp
RUN echo '' > /soarweb/manage.sh
RUN echo '#!/bin/bash' >> /soarweb/manage.sh
RUN echo 'function start(){' >> /soarweb/manage.sh
RUN echo '  if [ $(checkPid) ]; then' >> /soarweb/manage.sh
RUN echo '    echo \'soar web is running\'' >> /soarweb/manage.sh
RUN echo '  else' >> /soarweb/manage.sh
RUN echo '    nohup python3 /soarweb/app/soar-web.py > /dev/null 2>&1 &' >> /soarweb/manage.sh
RUN echo '    echo \'soar web start ....... ok\'' >> /soarweb/manage.sh
RUN echo '  fi' >> /soarweb/manage.sh
RUN echo '}' >> /soarweb/manage.sh
RUN echo '' >> /soarweb/manage.sh
RUN echo 'function stop(){' >> /soarweb/manage.sh
RUN echo '  pid=$(checkPid)' >> /soarweb/manage.sh
RUN echo '  if [ $pid ]; then' >> /soarweb/manage.sh
RUN echo '    kill -9 $pid' >> /soarweb/manage.sh
RUN echo '  fi' >> /soarweb/manage.sh
RUN echo '  echo \'soar web stop ....... ok\'' >> /soarweb/manage.sh
RUN echo '}' >> /soarweb/manage.sh
RUN echo '' >> /soarweb/manage.sh
RUN echo 'function restart() { >> /soarweb/manage.sh
RUN echo '    stop' >> /soarweb/manage.sh
RUN echo '    start' >> /soarweb/manage.sh
RUN echo '}' >> /soarweb/manage.sh
RUN echo '' >> /soarweb/manage.sh
RUN echo 'function checkPid(){' >> /soarweb/manage.sh
RUN echo '  ps ax | grep soar-web.py | grep -v grep  | awk \'{print $1}\'' >> /soarweb/manage.sh
RUN echo '}' >> /soarweb/manage.sh
RUN echo '' >> /soarweb/manage.sh
RUN echo 'if [ $1 ]; then' >> /soarweb/manage.sh
RUN echo '  $1' >> /soarweb/manage.sh
RUN echo 'fi' >> /soarweb/manage.sh
RUN chmod a+x /soarweb/manage.sh
CMD ["/soarweb/manage.sh"]
