#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @File  : config.py
# @Author: becivells
#@Contact : becivells@gmail.com
# @Date  : 2018/10/31
#@Software : PyCharm
# @Desc  :
import os

BASE_DIR = os.path.dirname(os.path.realpath(__file__))

soar_args = {
    "allow-drop-index": None,
    "allow-online-as-test": None,
    "alsologtostderr": None,
    "blacklist": str,
    "config": str,
    "conn-time-out": int,
    "delimiter": str,
    "drop-test-temporary": None,
    "dry-run": None,
    "explain": None,
    "explain-format": str,
    "explain-max-filtered": float,
    "explain-max-keys": int,
    "explain-max-rows": int,
    "explain-min-keys": int,
    "explain-sql-report-type": str,
    "explain-type": str,
    "explain-warn-access-type": str,
    "explain-warn-extra": str,
    "explain-warn-scalability": str,
    "explain-warn-select-type": str,
    "ignore-rules": str,
    "index-prefix": str,
    "list-heuristic-rules": None,
    "list-report-types": None,
    "list-rewrite-rules": None,
    "list-test-sqls": None,
    "log-level": int,
    "log-output": str,
    "log_backtrace_at": "value",
    "log_dir": str,
    "logtostderr": None,
    "markdown-extensions": int,
    "markdown-html-flags": int,
    "max-column-count": int,
    "max-distinct-count": int,
    "max-group-by-cols-count": int,
    "max-in-count": int,
    "max-index-bytes": int,
    "max-index-bytes-percolumn": int,
    "max-index-cols-count": int,
    "max-index-count": int,
    "max-join-table-count": int,
    "max-pretty-sql-length": int,
    "max-query-cost": int,
    "max-subquery-depth": int,
    "max-total-rows": int,
    "max-varchar-length": int,
    "online-dsn": str,
    "only-syntax-check": None,
    "print-config": None,
    "profiling": None,
    "query": str,
    "query-time-out": int,
    "report-css": str,
    "report-javascript": str,
    "report-title": str,
    "report-type": str,
    "rewrite-rules": str,
    "sampling": None,
    "sampling-statistic-target": int,
    "show-last-query-cost": None,
    "show-warnings": None,
    "spaghetti-query-length": int,
    "sql-max-length-errors": int,
    "sql-max-length-ui": int,
    "stderrthreshold": "value",
    "table-allow-charsets": str,
    "table-allow-engines": str,
    "test-dsn": str,
    "trace": None,
    "unique-key-prefix": str,
    "v": "value",
    "verbose": None,
    "version": None,
    "vmodule": "value",
}
